# Puerto de la aplicación
server.port=8080

# Configuración de Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d87jhs3bc2fs73f3jghg-a.ohio-postgres.render.com:5432/pedidos_final?sslmode=require
spring.datasource.username=admin
spring.datasource.password=K0uOGsFoG7QnkcsHzbQSYJovrRGPNhrj
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Permitir sobreescritura de beans
spring.main.allow-bean-definition-overriding=true

# JWT Configuration 
jwt.secret=clave-secreta-super-segura-apipedidos-2026-min32chars!!
jwt.expiration-ms=3600000
jwt.refresh-expiration-ms=86400000
